;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        end-of-buffer
        fill-paragraph
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        kill-region
        markdown-outdent-or-delete
        my-backward-kill-word
        my-kill-word
        org-beginning-of-line
        org-self-insert-command
        overwrite-mode
        sgml-slash
        web-mode-comment-or-uncomment
        ))

(setq mc/cmds-to-run-once
      '(
        company-complete
        helm-M-x
        magit-status
        toggle-frame-fullscreen
        ))
