;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-slash
        hungry-delete-backward
        hungry-delete-forward
        org-self-insert-command
        sgml-slash
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        ))
