;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        compro/comint/kill-word
        forward-sexp
        hungry-delete-backward
        hungry-delete-forward
        kill-sexp
        whole-line-or-region-kill-ring-save
        ))

(setq mc/cmds-to-run-once
      '(
        text-scale-adjust
        ))
